# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # The name of a custom docker image to use. The first image listed under a job defines the job’s own primary container image where all steps will run.
    # The list of official images: https://circleci.com/developer/images
    docker:
      - image: circleci/openjdk:17.0.1-jdk-buster

    working_directory: ~/RoomReservationService

    environment:
      MAVEN_OPTS: -Xmx3200m # max memory consumption

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      # Download and cache dependencies
      # Do not download new dependencies in case of pom.xml has not been changed
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "pom.xml"}}
            - v1-dependencies-

      # https://maven.apache.org/plugins/maven-dependency-plugin/go-offline-mojo.html
      - run: mvn dependency:go-offline

      - save_cache:
          key: v1-dependencies-{{checksum "pom.xml"}}
          paths:
            - ~/.m2

      - run:
          name: build and test project with maven
          command: mvn test install
